# Generated by Django 2.2.5 on 2019-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=400)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('organizer', models.CharField(max_length=200)),
            ],
        ),
    ]
